# Generated by Django 5.1.4 on 2025-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
