# Generated by Django 5.1.4 on 2025-01-29 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('number_eval_per_player', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicEvaluationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('pace', models.IntegerField(verbose_name='Vitesse et Acceleration')),
                ('assist', models.IntegerField(verbose_name='Passe')),
                ('defense', models.IntegerField(verbose_name='defense')),
                ('shoot', models.IntegerField(verbose_name='Puissance du tir')),
                ('dribble', models.IntegerField(verbose_name='Dribble')),
            ],
            options={
                'verbose_name': 'Fiche evaluation periodique',
                'verbose_name_plural': 'Fiches evaluation periodique',
            },
        ),
    ]
