# Generated by Django 5.1.4 on 2025-01-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='examiner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_made', to='players.player'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='player_examined',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='players.player'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_evaluations', to='evaluations.period'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.periodicevaluationsheet'),
        ),
    ]
