# Generated by Django 5.1.4 on 2025-03-25 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_game_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_type', models.CharField(choices=[('AND', 'All of'), ('OR', 'Any of')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.baseform')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='form_manager.baseform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('answer_type', models.CharField(choices=[('BOOLEAN', 'Yes/No'), ('STRING', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('RANGE', 'Range'), ('MULTIPLE_CHOICE', 'Multiple Choice')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('range_min', models.IntegerField(default=0)),
                ('range_max', models.IntegerField(default=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_manager.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConditionClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[(None, 'No operator selected'), ('NE', 'Not Equal'), ('EQ', 'Equal'), ('LE', 'Lower or Equal'), ('LT', 'Lower Than'), ('GE', 'Greater or Equal'), ('GT', 'Greater Than'), ('BT', 'Between'), ('any', 'Any')], max_length=10)),
                ('expected_value', models.CharField(max_length=200)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='form_manager.condition')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.question')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='target_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_conditions', to='form_manager.question'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='form_manager.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=500, null=True)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('range_value', models.IntegerField(blank=True, null=True)),
                ('choices', models.ManyToManyField(blank=True, to='form_manager.choice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form_manager.formresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_manager.question')),
            ],
        ),
    ]
